---
title: "Turnover Models Validation"
format: html
editor: visual
---

# Turnover Models Summary and Validation

# Model 1: Beta GLMM

jaccard_dissimilarity_beta \~ LC_change \* start_period + (1 \| SSBID)

### Model Output

```{r model1.1 summary}
load(here("data", "models", "model1.1_SSB.RData"))
summary(model1.1_SSB)
```

No effect of time, land cover changes or interaction on the turnover of species.

### Model Validation

```{r model1.1 residuals}
model1.1_simulated_residuals <- simulateResiduals(fittedModel = model1.1_SSB)
plot(model1.1_simulated_residuals)
```

### Test Overdispersion

```{r model1.1 check overdispersion}
testOverdispersion(model1.1_simulated_residuals)
```

### Test Zero Inflation of Residuals

```{r model1.1 residual zero inflation}
testZeroInflation(model1.1_simulated_residuals)
```

### Visualise Random Effects

```{r model 1.1. random effects}
dotplot(ranef(model1.1_SSB, condVar = TRUE))
```

### Check multicollinearity

```{r model1.1 multicollinearity}
vif(model1.1_SSB)
```
